### ISSUE TITLE
Only use a single CAP-project repository

### ISSUE THREAD

**Issue by sebasguts** [sebasguts/CategoriesForHomalg#36]
We should not use different git repositories for the different packages in the CAP project, which are atm CAP and ModulePresentations(ForHomalg). Instead, there should be one repository, containing at the root folder two folders for the packages. Advantages of this would be:
- Consistent versions of the packages in a repository. If one pulls the latest version, automatically all packages in the CAP project would be compatible and up-to-date, without any effort or taking care of it.
- Bugfixed could be done over more than one package, e.g., if a name is changed, this can be done in one commit for all the packages.
- Git bisect would work as intended.
- Git grep would work as intended.
- Tests would be much easier, since no incmpatible package versions are in the git repository any more. There could also be some tests for the whole project
- There could be a readme for the whole project.
- Installing the whole project from GitHub becomes easier, since only one repository has to be cloned.

The following would **NOT** be a disadvantage:
- Modularity is still given, even if one has to clone all the packages at once from Github, they do not need all to be loaded in a GAP session.
- Folder structure is not a problem, since GAP does not only look into the pkg directory for packages but at least one level deeper.
- If a change is made in only one package, merging would not be a problem, since it is done by files.

The following might be a disadvantage:
- History becomes much bigger.

After all, it seems that our workflow would be better if we only had one repository for both packages and for those to come.

It is possible to keep the history of the two repositories in the new one using git subtree.

**Comment by mohamed-barakat** [comment]
Sounds very good, also for some of homalg's packages. Is there a way to do this a posteriori?

**Comment by sebasguts** [comment]
Git subtree would be an option http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/ but would not have the desired effect as far as I understand. But I think there already is a script, or we can write one, so that it simply looks like a merge.

**Comment by sebasguts** [comment]
http://jasonkarns.com/blog/merge-two-git-repositories-into-one/ This seems to work.

**Comment by sebasguts** [comment]
https://github.com/sebasguts/CAPProject There is the result.

**Comment by mohamed-barakat** [comment]
I would suggest CAP_project

**Comment by mohamed-barakat** [comment]
:+1:
